#Fetched from the conan docs
os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
  - pip install conan
  - conan user
script:
  - mkdir build && cd build
  - conan install .. --build fmt
  - conan build ..
  - ctest 