#Fetched from the conan docs
os: linux

language: python
python: "3.7"

dist: xenial
addons:
  apt:
    packages: lcov

compiler:
  - gcc
install:
  - pip install conan
  - conan user
script:
  - mkdir build && cd build
  - conan install .. --build fmt
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug -- -j $(nproc)
  - ctest -j $(nproc) --output-on-failure 
after_success:
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' '*/tests/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"